.oh-my-zsh:
  type: archive
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h
.config/nvim:
  type: git-repo
  url: https://github.com/aoantov/lazyvim.git
  refreshPeriod: 168h
.oh-my-zsh/custom/plugins/jirarc:
  type: archive
  url: https://github.com/aoantov/jirarc/archive/refs/tags/v1.3.0.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

